<?php
// $Id:$

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function example_d8_menu() {
  $items['example/page'] = array(
    'title' => 'Example Page',
    'description' => 'This is the example page',
    'router_name' => 'example_page',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function example_d8_permission() {
  $permissions = array(
    'access example' => array(
      'title' => t('Access Example'),
      'description' => t('Access example page.'),
    ),
  );
  return $permissions;
}